language: java
sudo: false

jdk:
- openjdk11

cache:
  directories:
    - "$HOME/.m2/repository"

before_install:
- wget https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip
- unzip -qq apache-maven-3.6.0-bin.zip
- export M2_HOME=$PWD/apache-maven-3.6.0
- export PATH=$M2_HOME/bin:$PATH
- echo "MAVEN_OPTS='-Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc

install:
- mvn --version
- java --version

script:
- mvn --update-snapshots verify 

